#!/usr/bin/env bash
# Configuration of the Nginx server so you can have another page
# Redirecting configuration is now 301 moved completely

apt-get update
apt-get install -y nginx

mkdir /etc/nginx/html
touch /etc/nginx/html/index.html
echo "Hello ALX!" > /etc/nginx/html/index.html
printf %s "server {
    listen 80;
    listen [::]:80 default_server;
    root   /etc/nginx/html;
    index  index.html index.htm;
    location /redirect_me {
        return 301 https://youtu.be/BNmyYzosV-E?si=-Wn2abIY0JnkBRDe;
    }
}" > /etc/nginx/sites-available/default

service nginx restart

