#!/usr/bin/env bash
# Configuration of the nginx server

#scripts for creation in all
apt-get update
apt-get install -y nginx
#creates directory
mkdir /etc/nginx/html
#creates the index html
touch /etc/nginx/html/index.html
#prints hello world to the screen
echo "Hello World!" > /etc/nginx/html/index.html
touch /etc/nginx/html/404.html
#echo this to the file and means this is not a file in french
echo "Ceci n'est pas une page" > /etc/nginx/html/404.html

printf %s "server {
    listen 80;
    listen [::]:80 default_server;
    root   /etc/nginx/html;
    index  index.html index.htm;

    location /redirect_me {
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
    }

    error_page 404 /404.html;
    location /404 {
      root /etc/nginx/html;
      internal;
    }
}" > /etc/nginx/sites-available/default

#service starts now with this script
service nginx restart
