#!/usr/bin/env bash
# multiple operations to be done in one
terminator()
{
	#deletes the file
	rm /var/run/myscript.pid
	exit
}

#displays the ssid 
echo "$$" > /var/run/myscript.pid

#while loop to go through it all
while true
do
	echo "To infinity and beyond"
	sleep 2
	trap 'echo "Y U no love me?!"' SIGINT
	trap 'echo "I hate the kill command" && terminator' SIGTERM
	trap 'terminator' SIGQUIT
done


