#!/usr/bin/env bash
#checks if they exist in the context

school_name=school
if [ -e $school_name ]; then
    echo "school file exists"
else
    echo "school file does not exist"
    exit 1
fi
if [ ! -s $school_name ]; then
    echo "school file is empty"
else
    echo "school file is not empty"
fi
if [ -f $school_name ]; then
    echo "school is a regular file"
fi

