#!/usr/bin/env bash
#gets the ip address for this task 
ip_address=$(ip -4 addr show | grep inet | awk '{print $2}' | cut -d'/' -f1)

# Displays the IP address you know
printf "%-20s\n" "IPv4 ADDRESS"
printf "%-20s\n" "-------------"

# displays the ipadreesss
while read -r address_show; do
    
    printf "%-20s\n" "$address_show"
done <<< "$ip_address"
